"""One-page, printable HTML citizen report (open in a browser -> Print -> Save as PDF)."""
from __future__ import annotations

import html
import re

import pandas as pd

from analytics import AS_OF, ProjectAnalysis, fmt_inr

COLORS = {"Healthy": "#2e9e5b", "Watch": "#f0a202", "Red flag": "#d64545"}


def _md(text: str) -> str:
    """Tiny markdown subset (bold, italics, bullets) -> HTML, after escaping."""
    out, in_list = [], False
    for line in html.escape(text).split("\n"):
        line = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", line)
        line = re.sub(r"\*(.+?)\*", r"<i>\1</i>", line)
        if line.startswith("- "):
            out.append(("" if in_list else "<ul>") + f"<li>{line[2:]}</li>")
            in_list = True
            continue
        if in_list:
            out.append("</ul>")
            in_list = False
        out.append(f"<p>{line}</p>" if line.strip() else "")
    return "\n".join(out) + ("</ul>" if in_list else "")


def build_report_html(a: ProjectAnalysis, summary_md: str, reports: pd.DataFrame, audit_ok: bool) -> str:
    ev, color = a.ev, COLORS[a.status]
    kpis = [("Allocated", fmt_inr(a.allocated)), ("Spent", f"{fmt_inr(ev['ac'])} ({ev['spend_pct']:.0f}%)"),
            ("Work done", f"{ev['progress_pct']:.0f}%"), ("Time elapsed", f"{ev['planned_pct']:.0f}%"),
            ("Projected final cost", f"{fmt_inr(ev['eac'])} ({ev['overrun_pct']:+.0f}%)"),
            ("CPI / SPI", f"{ev['cpi']:.2f} / {ev['spi']:.2f}"), ("Worst milestone delay", f"{a.max_delay} days")]
    kpi_html = "".join(f"<div class='k'><span>{html.escape(k)}</span><b>{html.escape(v)}</b></div>" for k, v in kpis)
    flags = "".join(f"<li><b>{html.escape(f.title)}</b> <i>({f.severity})</i> - {html.escape(f.reason)}</li>"
                    for f in a.flags) or "<li>No red flags raised.</li>"
    top = reports.sort_values("upvotes", ascending=False).head(3)
    cit = "".join(f"<li>\"{html.escape(r.text)}\" - {r.upvotes} upvotes, {html.escape(r.status)}</li>"
                  for r in top.itertuples()) or "<li>No citizen reports.</li>"
    integrity = "intact (SHA-256 hash chain verified)" if audit_ok else "<b style='color:#d64545'>BROKEN - records were altered</b>"
    return f"""<!doctype html><html><head><meta charset="utf-8"><title>OurCity - {html.escape(a.name)}</title>
<style>body{{font-family:Arial,sans-serif;max-width:820px;margin:24px auto;color:#222}}
h1{{margin:0}} .badge{{display:inline-block;padding:4px 12px;border-radius:14px;color:#fff;background:{color};font-weight:bold}}
.grid{{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:16px 0}}
.k{{border:1px solid #ddd;border-radius:8px;padding:8px}} .k span{{display:block;font-size:12px;color:#666}}
footer{{margin-top:24px;font-size:12px;color:#777}}</style></head><body>
<h1>{html.escape(a.name)}</h1><p>{html.escape(a.sector)} - {a.project_id} - <span class="badge">{a.status} - risk {a.risk_score:.0f}/100</span></p>
<h3>In plain words</h3>{_md(summary_md)}
<div class="grid">{kpi_html}</div>
<h3>Red flags</h3><ul>{flags}</ul>
<h3>What citizens say</h3><ul>{cit}</ul>
<h3>Audit trail</h3><p>Integrity: {integrity}</p>
<footer>Generated by OurCity - data as of {AS_OF.isoformat()} - synthetic demo data.</footer></body></html>"""